#!/usr/bin/env python3
"""Select dishes of the day at build time (deterministic by CET date)."""

from __future__ import annotations

import hashlib
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content" / "menu"
OUTPUT = ROOT / "data" / "dishes_of_the_day.toml"
COUNT = 6
RE_FRONT_MATTER = re.compile(r"^\+{3}\s*\n(.*?)\n\+{3}", re.DOTALL)
RE_TITLE = re.compile(r'^title\s*=\s*"(.*?)"', re.MULTILINE)
RE_DESCRIPTION = re.compile(r'^description\s*=\s*"(.*?)"', re.MULTILINE)
RE_PATH = re.compile(r'^path\s*=\s*"(.*?)"', re.MULTILINE)


def slug_from_path(path_value: str, filename: str) -> str:
    if path_value.startswith("@/"):
        return path_value[2:].strip("/")
    if path_value:
        return path_value.strip("/").lstrip("/")
    return Path(filename).stem


def parse_recipe(path: Path) -> dict[str, str] | None:
    text = path.read_text(encoding="utf-8")
    match = RE_FRONT_MATTER.match(text)
    if not match:
        return None

    front = match.group(1)
    title_match = RE_TITLE.search(front)
    if not title_match:
        return None

    title = title_match.group(1)
    description = ""
    desc_match = RE_DESCRIPTION.search(front)
    if desc_match:
        description = desc_match.group(1)

    path_match = RE_PATH.search(front)
    path_value = path_match.group(1) if path_match else ""
    slug = slug_from_path(path_value, path.name)

    return {
        "title": title,
        "description": description,
        "slug": slug,
        "url": f"/{slug}/",
    }


def collect_recipes() -> list[dict[str, str]]:
    recipes: list[dict[str, str]] = []
    for path in sorted(CONTENT.rglob("*.md")):
        if path.name == "_index.md":
            continue
        recipe = parse_recipe(path)
        if recipe:
            recipes.append(recipe)
    return recipes


def score(slug: str, seed: str) -> str:
    return hashlib.sha256(f"{seed}:{slug}".encode()).hexdigest()


def select_dishes(recipes: list[dict[str, str]], seed: str, count: int) -> list[dict[str, str]]:
    ranked = sorted(recipes, key=lambda r: score(r["slug"], seed))
    return ranked[: min(count, len(ranked))]


def escape_toml(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_toml(dishes: list[dict[str, str]], seed: str) -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/dishes_of_the_day.py — do not edit",
        f'date = "{seed}"',
        "",
    ]

    if not dishes:
        lines.extend(
            [
                "[[dishes]]",
                'title = "No recipes yet"',
                'description = ""',
                'url = "/"',
            ]
        )
    else:
        for dish in dishes:
            lines.extend(
                [
                    "[[dishes]]",
                    f'title = "{escape_toml(dish["title"])}"',
                    f'description = "{escape_toml(dish["description"])}"',
                    f'url = "{escape_toml(dish["url"])}"',
                    "",
                ]
            )

    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def cet_now() -> datetime:
    try:
        return datetime.now(ZoneInfo("Europe/Rome"))
    except Exception:
        return datetime.now(timezone(timedelta(hours=1)))


def main() -> int:
    now = cet_now()
    seed = now.strftime("%d%m%Y")

    recipes = collect_recipes()
    if not recipes:
        print("Warning: no recipes found under content/menu/", file=sys.stderr)

    dishes = select_dishes(recipes, seed, COUNT)
    write_toml(dishes, seed)
    print(f"Selected {len(dishes)} dishes for {seed} (CET) -> {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
